name: Actualizacion Diaria de Promociones
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  build-and-refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v3

      - name: Configurar Python Oficial
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Dependencias de Datos
        run: |
          pip install pandas requests huggingface_hub geopy beautifulsoup4

      - name: Ejecutar Robot Extractor
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python scraper.py
        
